# Generated by Django 5.0.2 on 2024-10-07 09:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccapi', '0003_customerpurchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerpurchase',
            name='date',
        ),
        migrations.AlterField(
            model_name='customerpurchase',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='customerpurchase',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
