# Generated by Django 5.0.2 on 2024-10-07 09:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccapi', '0004_remove_customerpurchase_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpurchase',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='customerpurchase',
            name='amount',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='customerpurchase',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
