# Generated by Django 5.0.2 on 2024-10-07 09:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccapi', '0006_remove_customerpurchase_date_customerdetail_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerdetail',
            name='date',
        ),
        migrations.AddField(
            model_name='customerpurchase',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
