# Generated by Django 5.0.2 on 2024-10-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccapi', '0007_remove_customerdetail_date_customerpurchase_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=10)),
                ('company_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('photo_upload', models.ImageField(blank=True, null=True, upload_to='customer_photos/')),
            ],
        ),
    ]
