# Generated by Django 5.0.2 on 2024-10-15 09:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccapi', '0008_vendorpurchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employeecount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coconut_count', models.DecimalField(decimal_places=1, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='employeedetails',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='employeedetails',
            name='coconut_count',
        ),
        migrations.RemoveField(
            model_name='employeedetails',
            name='rate',
        ),
    ]
