# Generated by Django 5.0.2 on 2024-10-15 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccapi', '0009_employeecount_remove_employeedetails_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
