# Generated by Django 5.0.2 on 2024-10-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccapi', '0010_alter_employeedetails_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeecount',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
