# Generated by Django 5.0.2 on 2024-10-15 13:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccapi', '0011_alter_employeecount_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='vendorsales',
            fields=[
                ('vendorpurchase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ccapi.vendorpurchase')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('coconut_kobbari', models.PositiveIntegerField()),
            ],
            bases=('ccapi.vendorpurchase', models.Model),
        ),
    ]
