# Generated by Django 5.0.2 on 2024-10-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccapi', '0013_vendorsales_amount_vendorsales_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeedetails',
            name='employee',
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
